### PR TITLE
Coding style: use local include

### PR DESCRIPTION
**Pull request by abique**

### CODE REVIEW

**Comment by Earnestly** [comment]
Why?

**Comment by abique** [comment]
Because #include "" uses relative path.
While #include <> uses search path.

**Comment by abique** [comment]
And by the way you should also include standard headers first, not yours. That way your marcos will not mess with standard headers.

**Comment by Earnestly** [comment]
Oh I'm not disagreeing but you need explain why in the message body.  You also need to explain why using relative paths is better.  I would hate to see crap like `#include "../foo.h"` but that doesn't seem to be what you're advocating here.

**Comment by abique** [comment]
Do it as it please.

**Comment by Earnestly** [comment]
@abique I'm not the owner of this repository incase you didn't notice, however I think asking for a little justification is a reasonable request.

There's really no need to be callow.

**Pull request closed without merging**
