### PR TITLE
Added handling of libinput gesture events

### PR DESCRIPTION
**Pull request by Hummer12007**
This PR adds handling of libinput gesture events with API for gesture.swipe and gesture.pinch.

### CODE REVIEW

**Comment by Cloudef** [comment]
This looks good so far. But is missing the actual handling of the touch signals in compositor/seat.c. I think I've implemented everything that can be passed to wl programs, but maybe the protocol has been updated since. If the programs can't catch these and are mainly meant for compositor to be read the bool return value doesn't really make sense as the input won't go to client anyways.

**Comment by Hummer12007** [comment]
I'm working on it. Will push it in coming days.

**Comment by tinchou** [comment]
@Hummer12007 any updates?? can I be of any help?

**Comment by Hummer12007** [comment]
Oh, that reminds me. I'll take a look at during the week.

**Comment by johan-bjareholt** [comment]
Any updates?

**Comment by Hummer12007** [comment]
I forgot about it before, but it's definitely postponed now (as sway is probably migrating off wlc).

**Pull request closed without merging**
