### PR TITLE
Exposed api to grab pointer texture

### PR DESCRIPTION
**Pull request by Enerccio**
Provides a way to get either custom texture surface from client or default texture from render

### CODE REVIEW

**Comment by Cloudef** [comment]
What exactly is the use case for this?

**Comment by Enerccio** [comment]
well if you render everything yourself, you do need a way to grab the surface of the pointer (and the default render texture)

**Comment by Enerccio** [comment]
Personally I use it here: https://github.com/Enerccio/nyarlathotep-wm/blob/master/src/render.c#L401

**Comment by Cloudef** [comment]
If you want to render everything yourself. I would probably instead work on making this plugable https://github.com/Cloudef/wlc/blob/master/src/platform/render/render.c#L142-L150 so you can replace the renderer itself instead of clearing and drawing everything again.

**Comment by ammen99** [comment]
@Cloudef The compositor doesn't have to render everything again, if you want to do custom rendering, you can set the output mask to 0.

**Comment by Enerccio** [comment]
@Cloudef I looked at that, but that does actual rendering, but not the order of view render nor anything else. which is why I opted to actually render everything afterwards

I also tried to have custom renderer api (it's master of my fork actually) but for some reason, if I had empty render view, I would get black texture later when rendering myself

**Comment by Enerccio** [comment]
Here is the exposed api for render but I am not sure if it is in state to PR: https://github.com/Enerccio/wlc/

**Pull request closed without merging**
