### PR TITLE
Update keyboard leds when pressed

### PR DESCRIPTION
**Pull request by crondog**
Please let me know if you have a better way of doing this. This was the easiest/minimal changes that I could think of

### CODE REVIEW

**Comment by Cloudef** [comment]
This looks good. wlc_keyboard_update_leds could take bitmask instead of the wlc_keyboard struct though. You can also drop wlc_ prefix and remove the function prototype from keyboard.h and declare the function simply as static in keyboard.c since that's the only place it's used from.

**Comment by crondog** [comment]
Thanks for the suggestions. That is much better

**Comment by Cloudef** [comment]
Thanks, I'll give it a go later today.

**Comment by crondog** [comment]
Hmm so I received an email saying add an assert, but now I can't see it on gh. I think I added in the right place...

**Comment by Cloudef** [comment]
Yup, that's correct. Thanks

**Pull request merged**
