### PR TITLE
xdg_surface to negative value origin

### PR DESCRIPTION
**Pull request by athrungithub**
fix geometry origin to positive value

### CODE REVIEW

**Comment by athrungithub** [comment]
I sorry, no use it for now, introduces new bug in app with window decoration gtk (sure) same with weston-apps with window toolkit.
Error message:
compositor/seat/data.c: 150 @ wlc_data_device_manager_offer(): Tried to retrieve handle of wrong type (surface != data-source)

**Comment by Cloudef** [comment]
That message is not related to this pr, it's probably just bug in the clipboard support of wlc.
As for this PR, I'm not sure what issue does this fix. What I see this is potentially breaking tiling of windows with shadow as decorations and such.

**Comment by athrungithub** [comment]
i use dmenu with origin and width ej dmenu -l 20 -x 100 -y 200 -w 250 .
i compile bemenu with xdg_surface for set geometry, for same purpose but, need introduce origin x, y in negative value.  ej bemenu -l 20 -x -100 -y -200 -w 250

**Comment by Cloudef** [comment]
Clients cant set their x, y positions without extra protocol extension. (Which is frowned upon on wayland). Orbment just hardcodes bemenu at the top.

**Pull request closed without merging**
